# 版本
api_version: '0.0.1'

# DB
database:
  type: 'mysql'
  host: '169.254.222.1'
  port: '3306'
  dbname: 'test'
  user: 'root'
  password: 'root'
  charset: 'utf8mb4'
  prefix: ''

# redis
redis:
  host: '127.0.0.1'
  port: '6379'
  password: ~
  select: 0
  prefix: ''

# log
logs:
  log_max_files: 10

# jwt
jwt:
  secret_key: 'JF!bG^H#Xf9qS#bK'
  token_ttl: 3600